services:
  db:
    image: postgres:16-alpine
    container_name: pharmacy-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pharmacy
      POSTGRES_USER: pharmacy_user
      POSTGRES_PASSWORD: pharmacy_secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmacy_user -d pharmacy"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
      build:
        context: ./pharmacy-api
        dockerfile: Dockerfile
      container_name: pharmacy-api
      restart: unless-stopped
      ports:
        - "8080:8080"
      environment:
        DB_ADDR: db:5432
        DB_USER: pharmacy_user
        DB_PASSWORD: pharmacy_secret
        DB_NAME: pharmacy
      depends_on:
        db:
          condition: service_healthy
volumes:
  pgdata:
